# Generated by Django 5.2.17 on 2026-10-02 17:34

import django.db.models.deletion
from django.db import migrations, models


def link_existing_reservations_to_customers(apps, schema_editor):
    Customer = apps.get_model("restaurant", "Customer")
    Reservation = apps.get_model("restaurant", "Reservation")
    database = schema_editor.connection.alias

    for reservation in Reservation.objects.using(database).order_by("pk").iterator():
        customer, _ = Customer.objects.using(database).get_or_create(
            email=reservation.email,
            defaults={"name": reservation.name},
        )
        Reservation.objects.using(database).filter(pk=reservation.pk).update(
            customer_id=customer.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'email'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='restaurant.customer'),
        ),
        migrations.RunPython(link_existing_reservations_to_customers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='restaurant.customer'),
        ),
    ]
