# Generated by Django 5.2.17 on 2026-10-02 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_tables_and_assign_existing_reservations(apps, schema_editor):
    RestaurantTable = apps.get_model("restaurant", "RestaurantTable")
    Reservation = apps.get_model("restaurant", "Reservation")
    database = schema_editor.connection.alias
    tables = []

    for table_number in range(1, 21):
        table, _ = RestaurantTable.objects.using(database).get_or_create(
            table_number=table_number,
            defaults={"seats": 4, "is_active": True},
        )
        tables.append(table)

    occupied_slots = {}
    for reservation in Reservation.objects.using(database).order_by(
        "date", "time", "pk"
    ).iterator():
        slot = (reservation.date, reservation.time)
        occupied_table_ids = occupied_slots.setdefault(slot, set())
        table = next(
            (candidate for candidate in tables if candidate.pk not in occupied_table_ids),
            None,
        )
        if table is None:
            raise RuntimeError(
                "Cannot migrate reservations: more than 20 existing bookings "
                f"share {reservation.date} at {reservation.time}."
            )
        occupied_table_ids.add(table.pk)
        Reservation.objects.using(database).filter(pk=reservation.pk).update(
            table_id=table.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_customer_reservation_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveSmallIntegerField(unique=True)),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='restaurant.restauranttable'),
        ),
        migrations.RunPython(
            seed_tables_and_assign_existing_reservations,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='restaurant.restauranttable'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('table', 'date', 'time'), name='unique_table_reservation_slot'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('customer', 'date', 'time'), name='unique_customer_reservation_slot'),
        ),
    ]
